apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-app-deployment
  labels:
    app: cron-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cron-app
  template:
    metadata:
      labels:
        app: cron-app
    spec:
      containers:
      - name: cron
        image: ghcr.io/facuhannoch/cron_app:latest
        ports:
          - containerPort: 8082
        env:
          - name: DB_URL # mongo_uri
            value: mongodb://mongodb-service:27017