apiVersion: v1
kind: Service
metadata:
  name: cron-service
  labels:
    app: cron
spec:
  selector:
    app: cron-app
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: cron-app-api-port