apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  clusterIP: None
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: mongo-port