apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  type: None # to make a service healdess, we set type as none
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: defaultPort
  # ports: # Headless service do not include ip address ??