name: Build and Push cron app

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  USERNAME: facuhannoch
  IMAGE_NAME: cron_app
  # IMAGE_NAME: ${{ github.repository }}


jobs:

  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login into GitHub
        run: echo "${{ secrets.GH_PAT }}" | docker loggin ghrc.io --username ${{ env.USERNAME }} --password-stdin
      
      - name: Build Docker image
        working-directory: src
        run: docker build -t ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:latest .
      
      - name: Push Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:latest
      