name: Build and Push cron app

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  USERNAME: facuhannoch
  GH_PATH: secrets.GH_PAT
  IMAGE_NAME: cron_app
  # IMAGE_NAME: ${{ github.repository }}


jobs:

  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login into GitHub
        run: docker login --username ${{ env.USERNAME }} --password ${{ env.GH_PAT }} ${{ env.REGISTRY }}
      
      - name: Build Docker image
        working-directory: src
        run: docker build -t ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.CONTAINER_NAME }}:latest .
      
      - name: Push Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.CONTAINER_NAME }}:latest
      